### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by victorizbitskiy** [BiberM/ABAPParallelizationService#1]
Hi!
Cool tool, but can you add some documentation?
In particular, I'm wondering where this can be used and it would be nice to get some use cases.

**Comment by BiberM** [comment]
Hi,

did not see your comment, sorry.

I am still very deep in development and not yet done. That is why there isn't any dcumentation yet. I will deliver this within the readme or similar once this has a useable status.

**Comment by BiberM** [comment]
@victorizbitskiy I just wrote some documentation now. Could please give some feedback if that is sufficient or in what details are missing?

**Comment by victorizbitskiy** [comment]
@BiberM thanks, looks good to me 👍
